const B='http://127.0.0.1:3999', M='http://127.0.0.1:3014';
async function j(m,p,body,tok,h){const r=await fetch((p.startsWith('http')?'':B)+p,{method:m,redirect:'manual',headers:{'Content-Type':'application/json',...(tok?{Authorization:'Bearer '+tok}:{}),...(h||{})},body:body?JSON.stringify(body):undefined});let d;try{d=await r.json()}catch(e){d=null}return {s:r.status,d,h:r.headers};}
const { sql, pool, ADMIN, ADMIN_SENHA } = require('./comum');
let f=0; const ok=(c,t,x)=>{ console.log((c?'  OK ':'FALHA ')+t+(x!==undefined?'  → '+JSON.stringify(x):'')); if(!c) f++; };
const hook=(event,payment)=>j('POST','/webhook/asaas',{event,payment},null,{'asaas-access-token':'tokenwebhook123'});
(async()=>{
  await j('POST',M+'/_reset');
  await sql("delete from loja_desbloqueios; delete from loja_pedidos; delete from loja_aulas; delete from loja_produtos; delete from loja_professores; delete from sistema_cfg;");
  await sql("delete from users where email in ('al1@x.com')");
  const SA=(await j('POST','/user/login',{email:ADMIN,password:ADMIN_SENHA})).d.token;
  const rot=JSON.stringify({v:1,aula:'Teste',blocos:[{z:'z1',dur:5},{z:'z3',dur:10},{z:'z5',dur:4},{z:'z2',dur:6}],a:[[0,0,0,'g',0,0,0]]});
  const g1=(await sql(`insert into aulas_gravadas (license_id,nome_aula,professor,dur_seg,roteiro,status,teste_ate) values ('D5448D47','Aula Teste Loja','Mario',1500,'${rot}','teste',now()+interval '72 hours') returning id`)).split('\n')[0];
  const g2=(await sql(`insert into aulas_gravadas (license_id,nome_aula,professor,dur_seg,roteiro,status) values ('D5448D47','Aula 2','Mario',1500,'${rot}','no_pc') returning id`)).split('\n')[0];
  console.log('1) Abastecer (super admin)');
  let pr=(await j('POST','/admin/loja/professores',{nome:'Mario Elite',bio:'Treinador de ciclismo',cidade:'São Paulo'},SA)).d; ok(pr.id,'professor criado');
  let a1=(await j('POST','/admin/loja/aulas',{gravada_id:g1,professor_id:pr.id,titulo:'Endurance 25',preco:'19,90',video_url:'https://www.dropbox.com/scl/fi/abc/aula.webm?rlkey=x&dl=0'},SA)).d;
  ok(a1.preco==19.9 && /^https:\/\/dl\.dropboxusercontent\.com\/scl\/fi\/abc\/aula\.webm\?rlkey=x$/.test(a1.video_url) && !/dl=0/.test(a1.video_url),'aula R$19,90 com link do Dropbox convertido',a1.video_url);
  ok(await sql(`select status from aulas_gravadas where id=${g1}`)==='loja','gravação presa à loja (não apaga em 72 h)');
  let a2=(await j('POST','/admin/loja/aulas',{gravada_id:g2,professor_id:pr.id,titulo:'Força 25',preco:15},SA)).d;
  let a3=(await j('POST','/admin/loja/aulas',{gravada_id:g2,professor_id:pr.id,titulo:'Grátis',preco:0},SA)).d;
  let pk=(await j('POST','/admin/loja/produtos',{nome:'Pacote 3 aulas',tipo:'pacote',creditos:3,dias:60,preco:39.9,preco_de:59.7,destaque:true},SA)).d; ok(pk.id,'pacote criado');
  let as=(await j('POST','/admin/loja/produtos',{nome:'Assinatura mensal',tipo:'assinatura',dias:30,preco:49},SA)).d; ok(as.id,'assinatura criada');
  ok((await j('POST','/admin/loja/produtos',{nome:'X',tipo:'pacote',creditos:0,preco:10},SA)).s===400,'pacote sem crédito recusado');
  console.log('2) Vitrine com vendas desligadas');
  await j('POST','/user/register',{name:'Aluno Um',email:'al1@x.com',password:'123456',aceite_termos:true,aceite_saude:true}); const A=(await j('POST','/user/login',{email:'al1@x.com',password:'123456',aceite_termos:true,aceite_saude:true})).d.token;
  let v=(await j('GET','/loja',null,A)).d; ok(v.vendas_ligadas===false && v.aulas.length===3 && v.produtos.length===2 && v.professores[0].aulas===3,'vitrine',{aulas:v.aulas.length,prod:v.produtos.length});
  ok(v.aulas.find(x=>x.id===a3.id).tem_acesso && !v.aulas.find(x=>x.id===a1.id).tem_acesso,'grátis liberada, paga bloqueada');
  ok(v.aulas.find(x=>x.id===a1.id).blocos.length===4,'aula traz os blocos do gráfico');
  ok((await j('GET','/loja')).s===200,'vitrine abre sem login');
  ok((await j('POST','/loja/comprar',{tipo:'aula',id:a1.id},A)).s===403,'comprar com vendas desligadas → Em breve');
  ok((await j('GET','/gravadas/'+g1+'/roteiro',null,A)).s===404,'aula paga não abre sem comprar');
  console.log('3) Ligar vendas e comprar aula avulsa');
  ok((await j('PUT','/admin/loja/cfg',{vendas:true},SA)).d.vendas===true,'vendas ligadas');
  let c=await j('POST','/loja/comprar',{tipo:'aula',id:a1.id},A); ok(c.s===400&&c.d.precisa_cpf,'pede CPF na 1ª compra');
  c=await j('POST','/loja/comprar',{tipo:'aula',id:a1.id,cpf_cnpj:'123.456.789-09'},A); ok(c.s===200&&c.d.url,'cobrança gerada',c.d);
  let st=(await j('GET',M+'/_state')).d, pay=Object.values(st.pays).find(x=>x.externalReference==='loja:'+c.d.pedido_id);
  ok(pay&&pay.billingType==='UNDEFINED'&&pay.value===19.9,'Asaas: PIX/cartão/boleto, R$ 19,90');
  ok(await sql("select count(*) from information_schema.columns where table_name='users' and column_name like 'cpf%'")==='0', 'CPF não é guardado');
  await hook('PAYMENT_RECEIVED',{...pay,status:'RECEIVED',billingType:'PIX'});
  ok((await j('GET','/loja/pedidos/'+c.d.pedido_id,null,A)).d.status==='pago','pedido pago');
  v=(await j('GET','/loja',null,A)).d; ok(v.aulas.find(x=>x.id===a1.id).tem_acesso,'aula liberada');
  ok((await j('GET','/gravadas/'+g1+'/roteiro',null,A)).s===200,'roteiro abre');
  let vid=await j('GET','/gravadas/'+g1+'/video?t='+A); ok(vid.s===302&&/dropbox/.test(vid.h.get('location')),'vídeo vem do link',vid.s);
  ok((await j('POST','/loja/comprar',{tipo:'aula',id:a1.id},A)).s===400,'não compra de novo');
  console.log('4) Pacote de créditos');
  c=await j('POST','/loja/comprar',{tipo:'produto',id:pk.id},A); st=(await j('GET',M+'/_state')).d; pay=Object.values(st.pays).find(x=>x.externalReference==='loja:'+c.d.pedido_id);
  await hook('PAYMENT_CONFIRMED',{...pay,status:'CONFIRMED',billingType:'CREDIT_CARD'});
  v=(await j('GET','/loja',null,A)).d; ok(v.minha.creditos===3,'3 créditos',v.minha);
  let u=await j('POST','/loja/aulas/'+a2.id+'/usar-credito',null,A); ok(u.d.ok&&u.d.creditos===2,'usou 1 crédito',u.d);
  v=(await j('GET','/loja',null,A)).d; ok(v.aulas.find(x=>x.id===a2.id).tem_acesso&&v.minha.creditos===2,'aula 2 liberada, restam 2');
  await hook('PAYMENT_REFUNDED',{...pay,status:'REFUNDED'});
  v=(await j('GET','/loja',null,A)).d; ok(!v.aulas.find(x=>x.id===a2.id).tem_acesso&&v.minha.creditos===0,'estorno tira créditos e a aula');
  console.log('5) Assinatura e cortesia');
  ok((await j('POST','/admin/loja/cortesia',{email:'al1@x.com',tipo:'produto',id:as.id},SA)).d.ok,'cortesia: assinatura');
  v=(await j('GET','/loja',null,A)).d; ok(v.aulas.every(x=>x.tem_acesso)&&v.minha.assinaturas.length===1,'assinatura libera todas');
  let rp=(await j('GET','/admin/loja/repasse',null,SA)).d; ok(rp.professores.length&&Number(rp.vendas.total)>0,'repasse do mês',rp);
  ok((await j('DELETE','/admin/loja/aulas/'+a1.id,null,SA)).d.desativado,'aula vendida só desativa');
  let ad=(await j('GET','/admin/loja',null,SA)).d; ok(ad.gravacoes.length>=2&&ad.pedidos.length>=3,'admin vê gravações e pedidos');
  console.log(f?f+' FALHA(S)':'TUDO OK'); await pool.end(); process.exit(f?1:0);
})();
