const B='http://127.0.0.1:3999', M='http://127.0.0.1:3014';
async function j(m,p,body,tok,h){const r=await fetch((p.startsWith('http')?'':B)+p,{method:m,headers:{'Content-Type':'application/json',...(tok?{Authorization:'Bearer '+tok}:{}),...(h||{})},body:body?JSON.stringify(body):undefined});let d;try{d=await r.json()}catch(e){d=null}return {s:r.status,d};}
const { sql, pool, ADMIN, ADMIN_SENHA } = require('./comum');
const hoje=new Date(Date.now()-3*3600000).toISOString().slice(0,10);
const mais=(iso,d)=>new Date(Date.parse(iso)+d*86400000).toISOString().slice(0,10);
const mm=(iso,n=1)=>{const [y,m,d]=iso.split('-').map(Number);const t=new Date(Date.UTC(y,m-1+n,1));const u=new Date(Date.UTC(t.getUTCFullYear(),t.getUTCMonth()+1,0)).getUTCDate();t.setUTCDate(Math.min(d,u));return t.toISOString().slice(0,10);};
let falhas=0; const ok=(c,t,x)=>{ console.log((c?'  OK ':'FALHA ')+t+(x!==undefined?'  → '+JSON.stringify(x):'')); if(!c) falhas++; };
const WH={'asaas-access-token':'tokenwebhook123'};
const hook=(event,payment)=>j('POST','/webhook/asaas',{event,payment},null,WH);
(async()=>{
  await j('POST',M+'/_reset');
  await sql("delete from users where email in ('g2@x.com','f2@x.com')"); await sql("delete from licencas where nome='Demo Teste PG'");
  const SA=(await j('POST','/user/login',{email:ADMIN,password:ADMIN_SENHA})).d.token;
  const V1=mais(hoje,1);
  console.log('1) Criar licença (vence amanhã', V1+')');
  let r=await j('POST','/admin/licencas',{nome:'Demo Teste PG',max_bikes:12,valor_mensal:199,vencimento:V1,gestor_nome:'Gê',gestor_email:'g2@x.com',financeiro_nome:'Fê Fin',financeiro_email:'f2@x.com'},SA);
  const L=r.d; ok(r.s===200,'criada',L.codigo);
  ok(/^PR-/.test(L.gestor.senha_provisoria)&&/^PR-/.test(L.financeiro.senha_provisoria),'senhas provisórias criadas');
  ok(L.gestor.email_enviado===true || /RESEND_API_KEY/.test(L.gestor.email_motivo||''),'e-mail com a senha (enviado, ou o motivo)',L.gestor.email_motivo||'enviado');
  let li=(await j('GET','/admin/licencas',null,SA)).d.find(x=>x.id===L.id);
  ok(li.situacao==='a_vencer'&&li.proximo_vencimento===V1&&li.vencimento===V1,'lista: a vencer, vence '+V1,[li.situacao,li.proximo_vencimento,li.vencimento]);
  console.log('2) Financeiro entra com a senha provisória');
  let F=(await j('POST','/user/login',{email:'f2@x.com',password:L.financeiro.senha_provisoria})).d;
  ok(F.user.financeiro&&F.user.senha_provisoria,'login → financeiro + provisória');
  ok((await j('GET','/user/me',null,F.token)).d.financeiro===true,'/user/me traz financeiro');
  let G=(await j('POST','/user/login',{email:'g2@x.com',password:L.gestor.senha_provisoria})).d; ok(G.user.role==='gestor'&&!G.user.financeiro,'gestor entra como gestor');
  r=await j('GET','/academia/financeiro',null,F.token); ok(r.d.situacao==='a_vencer'&&r.d.proximo_vencimento===V1,'página: a vencer, próximo '+V1,[r.d.situacao,r.d.proximo_vencimento]);
  console.log('3) Pagar: a 1ª fatura tem que vencer em', V1,'(não hoje)');
  r=await j('POST','/academia/financeiro/pagar',{nome:'Demo',cpf_cnpj:'12345678000190'},F.token);
  ok(r.s===200&&r.d.url&&r.d.vencimento===V1,'fatura no vencimento certo',r.d);
  let st=(await j('GET',M+'/_state')).d; const sub=Object.keys(st.subs)[0]; let pay=Object.values(st.pays)[0];
  ok(st.subs[sub].externalReference===L.codigo,'assinatura com externalReference');
  console.log('4) Admin muda o vencimento → fatura do Asaas acompanha');
  const V2=mais(hoje,5);
  r=await j('PUT','/admin/licencas/'+L.id,{...li,vencimento:V2,gestor_email:'g2@x.com',financeiro_email:'f2@x.com',financeiro_nome:'Fê Fin'},SA);
  st=(await j('GET',M+'/_state')).d; pay=st.pays[pay.id];
  ok(pay.dueDate===V2&&st.subs[sub].nextDueDate===mm(V2),'fatura → '+V2+', assinatura → '+mm(V2),[pay.dueDate,st.subs[sub].nextDueDate]);
  ok(r.d.proximo_vencimento===V2,'resposta PUT traz próximo vencimento');
  console.log('5) Cartão pago (webhook CONFIRMED + RECEIVED repetido)');
  await j('POST',M+'/_pay/'+pay.id,{status:'CONFIRMED',confirmedDate:hoje}); pay={...pay,status:'CONFIRMED',confirmedDate:hoje};
  ok((await j('POST','/webhook/asaas',{event:'PAYMENT_CONFIRMED',payment:pay})).s===401,'webhook sem token recusado');
  ok((await hook('PAYMENT_CONFIRMED',pay)).s===200,'webhook ok');
  await hook('PAYMENT_RECEIVED',{...pay,status:'RECEIVED',paymentDate:hoje});
  ok(await sql(`select count(*) from pagamentos where license_id='${L.codigo}'`)==='1','sem duplicar');
  r=await j('GET','/admin/pagamentos/'+L.codigo,null,SA);
  ok(r.d.licenca.situacao==='em_dia'&&r.d.licenca.pago_ate===mm(V2)&&r.d.licenca.proximo_vencimento===mm(V2),'em dia, pago até '+mm(V2),[r.d.licenca.situacao,r.d.licenca.pago_ate,r.d.licenca.proximo_vencimento]);
  ok(r.d.pagamentos[0].origem==='asaas'&&r.d.pagamentos[0].metodo==='Cartão (Asaas)','linha do Asaas',r.d.pagamentos[0].metodo);
  ok((await j('DELETE','/admin/pagamentos/'+L.codigo+'/'+r.d.pagamentos[0].id,null,SA)).s===400,'Desfazer pagamento do Asaas é recusado (estorna lá)');
  ok(await sql(`select status from licencas where codigo='${L.codigo}'`)==='ativa','GET pagamentos não bloqueia mais a licença');
  console.log('6) Estorno no Asaas → volta');
  await hook('PAYMENT_REFUNDED',{...pay,status:'REFUNDED'}); await j('POST',M+'/_pay/'+pay.id,{status:'REFUNDED'});
  r=await j('GET','/admin/pagamentos/'+L.codigo,null,SA);
  ok(r.d.licenca.proximo_vencimento===V2&&!r.d.licenca.pago_ate&&r.d.licenca.situacao==='a_vencer','vencimento volta para '+V2,[r.d.licenca.situacao,r.d.licenca.pago_ate,r.d.licenca.proximo_vencimento]);
  console.log('7) Registro manual (por fora)');
  ok((await j('POST','/admin/pagamentos/'+L.codigo,{valor:199,metodo:'cartao',confirmo:true},SA)).s===400,'cartão manual recusado');
  ok((await j('POST','/admin/pagamentos/'+L.codigo,{valor:199,metodo:'pix'},SA)).s===400,'sem confirmação recusado');
  r=await j('POST','/admin/pagamentos/'+L.codigo,{valor:199,metodo:'pix',confirmo:true},SA);
  ok(r.d.cobre_de===V2&&r.d.cobre_ate===mm(V2)&&r.d.situacao==='em_dia','PIX cobre '+V2+' → '+mm(V2),r.d);
  st=(await j('GET',M+'/_state')).d; ok(st.subs[sub].nextDueDate===mm(V2),'Asaas: próxima cobrança só em '+mm(V2),st.subs[sub].nextDueDate);
  const idm=r.d.id; r=await j('DELETE','/admin/pagamentos/'+L.codigo+'/'+idm,null,SA);
  ok(r.d.proximo_vencimento===V2&&r.d.situacao==='a_vencer','Desfazer: volta para '+V2,[r.d.situacao,r.d.proximo_vencimento]);
  console.log('8) "Recebido em dinheiro" marcado no Asaas e desfeito (o caso do Demo 2)');
  const p3={id:'pay_cash'+Date.now(),subscription:sub,customer:'cus_x',value:199,status:'RECEIVED_IN_CASH',dueDate:V2,billingType:'CREDIT_CARD',paymentDate:hoje};
  await hook('PAYMENT_RECEIVED',p3);
  let x=(await j('GET','/admin/pagamentos/'+L.codigo,null,SA)).d; ok(x.licenca.situacao==='em_dia'&&/dinheiro/.test(x.pagamentos[0].metodo),'achou pela assinatura (sem externalReference) e marcou',x.pagamentos[0].metodo);
  await hook('PAYMENT_RECEIVED_IN_CASH_UNDONE',{...p3,status:'PENDING'});
  x=(await j('GET','/admin/pagamentos/'+L.codigo,null,SA)).d; ok(x.licenca.situacao==='a_vencer'&&x.licenca.proximo_vencimento===V2,'desfeito no Asaas → volta',[x.licenca.situacao,x.licenca.proximo_vencimento]);
  console.log('9) Cartão recusado');
  await hook('PAYMENT_CREDIT_CARD_CAPTURE_REFUSED',{...pay,id:'pay_r',status:'PENDING'});
  ok(/recusado/.test((await j('GET','/academia/financeiro',null,F.token)).d.aviso||''),'aviso na página do financeiro');
  console.log('10) TV: suspensa quando pago e +5 dias vencido');
  await sql(`update licencas set pagamento_ok_ate='${mais(hoje,-10)}', vencimento='${mais(hoje,-10)}' where codigo='${L.codigo}'`);
  r=await j('POST','/display/ativar',{codigo:L.codigo,device_id:'devpg'}); ok(r.s===403,'ativar recusado',r.d);
  ok((await j('GET','/admin/licencas',null,SA)).d.find(x=>x.id===L.id).situacao==='suspenso','admin vê suspenso');
  await sql(`update licencas set pagamento_ok_ate='${mais(hoje,-3)}', vencimento='${mais(hoje,-3)}' where codigo='${L.codigo}'`);
  r=await j('POST','/display/ativar',{codigo:L.codigo,device_id:'devpg'}); ok(r.s===200,'3 dias vencido: TV ainda funciona'); 
  ok((await j('GET','/admin/financeiro/dashboard',null,SA)).d.licencas.find(x=>x.id===L.id).situacao==='vencido','dashboard: vencido');
  console.log('11) Modal financeiro: data de vencimento');
  r=await j('PATCH','/admin/licencas/'+L.id+'/financeiro',{financeiro_email:'f2@x.com',financeiro_nome:'Fê Fin',vencimento:mais(hoje,10),valor_mensal:249},SA);
  ok(r.d.proximo_vencimento===mais(hoje,10)&&r.d.situacao==='em_dia','novo vencimento',[r.d.situacao,r.d.proximo_vencimento]);
  st=(await j('GET',M+'/_state')).d; ok(st.subs[sub].value===249,'valor no Asaas = 249');
  console.log('12) Nova senha + reenviar');
  r=await j('POST','/admin/licencas/'+L.id+'/reenviar-acesso',{papel:'financeiro'},SA);
  ok(/^PR-/.test(r.d.senha_provisoria),'nova senha',r.d.email_enviado?'enviada por e-mail':r.d.email_motivo);
  ok((await j('POST','/user/login',{email:'f2@x.com',password:r.d.senha_provisoria})).d.user.senha_provisoria===true,'entra com a nova');
  console.log('13) Excluir licença cancela a assinatura');
  r=await j('DELETE','/admin/licencas/'+L.id,null,SA); st=(await j('GET',M+'/_state')).d;
  ok(r.d.ok&&st.subs[sub].deleted,'cancelada no Asaas',r.d);
  console.log(falhas?'\n'+falhas+' FALHA(S)':'\nTUDO OK'); process.exit(falhas?1:0);
})();
