// 03/10e — segurança e saúde (rodar com o servidor ligado ao Resend simulado: EXTRA="RESEND_API_KEY=re_teste RESEND_API_URL=http://127.0.0.1:3014/emails EMAIL_FROM=..." )
const B='http://127.0.0.1:3999', M='http://127.0.0.1:3014';
async function j(m,p,body,tok,h){const r=await fetch((p.startsWith('http')?'':B)+p,{method:m,headers:{'Content-Type':'application/json',...(tok?{Authorization:'Bearer '+tok}:{}),...(h||{})},body:body?JSON.stringify(body):undefined});let d;try{d=await r.json()}catch(e){d=null}return {s:r.status,d};}
const { sql, pool, ADMIN, ADMIN_SENHA } = require('./comum');
let f=0; const ok=(c,t,x)=>{ console.log((c?'  OK ':'FALHA ')+t+(x!==undefined?'  → '+JSON.stringify(x):'')); if(!c) f++; };
(async()=>{
  await sql("delete from users where email like 'seg%@x.com'");
  const IP=n=>({'X-Forwarded-For':'10.0.0.'+n});
  console.log('1) Login com limite');
  await j('POST','/user/register',{name:'Seg Um',email:'seg1@x.com',password:'123456'},null,IP(1));
  for(let i=0;i<8;i++) await j('POST','/user/login',{email:'seg1@x.com',password:'errada'},null,IP(2));
  let r=await j('POST','/user/login',{email:'seg1@x.com',password:'123456'},null,IP(3)); ok(r.s===429,'9ª tentativa bloqueada (mesmo com a senha certa)',r.d);
  r=await j('POST','/user/login',{email:'nao-existe@x.com',password:'x'},null,IP(4)); ok(r.s===401,'outro e-mail continua normal');
  console.log('2) Esqueci minha senha');
  await j('POST',M+'/_reset');
  r=await j('POST','/user/esqueci-senha',{email:'seg1@x.com'},null,IP(5)); ok(r.d.ok,'pedido aceito',r.d.msg);
  r=await j('POST','/user/esqueci-senha',{email:'ninguem@x.com'},null,IP(5)); ok(r.d.ok,'e-mail sem conta responde igual (não revela)');
  const em=(await j('GET',M+'/_emails')).d.filter(e=>/senha nova/i.test(e.subject)); ok(em.length===1&&em[0].to[0]==='seg1@x.com','1 e-mail enviado, só para quem tem conta',em.map(e=>e.to));
  const tok=(em[0].html.match(/redefinir\.html\?t=([a-f0-9]{64})/)||[])[1]; ok(!!tok,'link com token no e-mail');
  ok((await j('POST','/user/redefinir-senha',{token:tok,senha:'123'})).s===400,'senha curta recusada');
  r=await j('POST','/user/redefinir-senha',{token:tok,senha:'novaSenha9'}); ok(r.d.ok,'senha trocada pelo link');
  ok((await j('POST','/user/redefinir-senha',{token:tok,senha:'outra123'})).s===400,'link usado não vale de novo');
  r=await j('POST','/user/login',{email:'seg1@x.com',password:'novaSenha9'},null,IP(6)); ok(r.s===200,'entra com a senha nova (e o bloqueio foi zerado)');
  const T=r.d.token;
  for(let i=0;i<3;i++) await j('POST','/user/esqueci-senha',{email:'seg1@x.com'},null,IP(7));
  ok((await j('POST','/user/esqueci-senha',{email:'seg1@x.com'},null,IP(8))).s===429,'4º pedido na mesma hora bloqueado');
  console.log('3) TV: código errado');
  for(let i=0;i<20;i++) await j('POST','/display/ativar',{codigo:'XXXX'+i,device_id:'d'},null,IP(9));
  ok((await j('POST','/display/ativar',{codigo:'D5448D47',device_id:'d'},null,IP(9))).s===429,'21º chute do mesmo IP bloqueado');
  console.log('4) Reportar problema');
  r=await j('POST','/suporte/relato',{texto:'A bike 3 não aparece',origem:'app',tela:'sConnect',versao:'03/10e'},T,IP(10)); ok(r.d.ok,'relato gravado');
  ok((await j('POST','/suporte/relato',{texto:'oi'},null,IP(10))).s===400,'relato vazio recusado');
  console.log('5) Modo suporte não é admin');
  const SA=(await j('POST','/user/login',{email:ADMIN,password:ADMIN_SENHA},null,IP(11))).d.token;
  const IMP=(await j('POST','/admin/impersonate/D5448D47',null,SA)).d.token;
  ok((await j('GET','/admin/licencas',null,IMP)).s===403,'token do modo suporte NÃO abre /admin/licencas');
  ok((await j('GET','/admin/licencas',null,SA)).s===200,'super admin continua abrindo');
  console.log('6) Saúde do sistema');
  const sd=(await j('GET','/admin/saude',null,SA)).d;
  ok(sd.banco.ok&&sd.email.provedor==='resend'&&sd.relatos.some(x=>/bike 3/.test(x.texto)),'mostra banco, e-mail e o relato',{banco:sd.banco,email:sd.email});
  ok(sd.eventos.some(e=>/login bloqueado/.test(e.msg)),'evento do bloqueio de login registrado');
  ok(sd.alertas.length>=1,'alertas',sd.alertas.map(a=>a.txt));
  const rid=sd.relatos.find(x=>/bike 3/.test(x.texto)).id; ok((await j('POST','/admin/saude/relatos/'+rid+'/resolver',null,SA)).d.ok,'relato resolvido');
  ok((await j('GET','/ping')).s===200,'/ping 200 com banco no ar');
  console.log('6b) Trocou a senha: os outros aparelhos saem');
  await j('POST','/user/register',{name:'Seg Dois',email:'seg2@x.com',password:'123456'},null,IP(20));
  const celA=(await j('POST','/user/login',{email:'seg2@x.com',password:'123456'},null,IP(21))).d.token;
  const pcB=(await j('POST','/user/login',{email:'seg2@x.com',password:'123456'},null,IP(22))).d.token;
  ok((await j('GET','/user/me',null,celA)).s===200,'celular logado');
  await new Promise(r=>setTimeout(r,1100));
  r=await j('PUT','/user/senha',{senha_atual:'123456',nova:'trocada77'},pcB); ok(r.d.ok&&r.d.token,'troca no computador devolve um token novo');
  ok((await j('GET','/user/me',null,celA)).s===401,'celular com a senha antiga saiu');
  ok((await j('GET','/user/me',null,pcB)).s===401,'token antigo do computador também não vale');
  ok((await j('GET','/user/me',null,r.d.token)).s===200,'computador segue logado com o token novo');
  ok((await j('POST','/user/login',{email:'seg2@x.com',password:'trocada77'},null,IP(23))).s===200,'login com a senha nova');
  const celC=(await j('POST','/user/login',{email:'seg2@x.com',password:'trocada77'},null,IP(24))).d.token;
  await new Promise(r=>setTimeout(r,1100));
  await j('POST',M+'/_reset'); await j('POST','/user/esqueci-senha',{email:'seg2@x.com'},null,IP(25));
  const tk2=((await j('GET',M+'/_emails')).d.filter(e=>/senha nova/i.test(e.subject)).pop().html.match(/t=([a-f0-9]{64})/)||[])[1];
  await j('POST','/user/redefinir-senha',{token:tk2,senha:'porlink88'});
  ok((await j('GET','/user/me',null,celC)).s===401,'"esqueci a senha" também derruba as sessões abertas');
  const D=(await j('POST','/display/ativar',{codigo:'D5448D47',device_id:'dseg'},null,IP(26))).d.token;
  ok((await j('GET','/display/licenca',null,D)).s===200,'TV não é afetada');
  console.log('7) Excluir minha conta');
  ok((await j('DELETE','/user/conta',{senha:'errada'},T)).s===401,'pede a senha');
  r=await j('DELETE','/user/conta',{senha:'novaSenha9'},T); ok(r.d.ok,'conta excluída');
  ok((await sql("select email||'|'||name||'|'||coalesce(peso::text,'-') from users where email like 'excluida-%' order by id desc limit 1")).startsWith('excluida-'),'dados pessoais apagados');
  ok((await j('POST','/user/login',{email:'seg1@x.com',password:'novaSenha9'},null,IP(12))).s===401,'não entra mais');
  console.log(f?f+' FALHA(S)':'TUDO OK'); await pool.end(); process.exit(f?1:0);
})();
